// =============================================================================
// SimAll Beta - GUI Subsystem
// File   : src/gui/PropertyEditor.hpp
// Phase  : 2.2 (PROPERTY EDITOR) — metadata-driven, dynamic widget creation.
//
// Builds editors from a list of PropertyDescriptor (Section 3.10 of spec).
// Widgets are generated by type — Double → QDoubleSpinBox with min/max,
// Bool → QCheckBox, Enum → QComboBox, String → QLineEdit. Visibility is
// re-evaluated on every value change via the descriptor's visibilityCondition.
// =============================================================================
#pragma once

#include <QWidget>
#include <functional>
#include <string>
#include <variant>
#include <vector>

class QFormLayout;

namespace simall::gui {

enum class PropertyType { Double, Int, Bool, Enum, String, Vec3 };

using Variant = std::variant<double, int, bool, std::string,
                             std::array<double,3>>;

struct PropertyDescriptor {
    std::string  propertyName;
    PropertyType type             = PropertyType::Double;
    Variant      defaultValue     = double{0};
    double       minimum          = -1e300;
    double       maximum          =  1e300;
    std::vector<std::string> enumOptions;
    std::string  tooltip;
    std::string  units;
    bool         requiresRestart  = false;
    std::function<bool()> visibilityCondition;
    std::function<void(const Variant&)> onChanged;
};

class PropertyEditor : public QWidget {
    Q_OBJECT
public:
    explicit PropertyEditor(QWidget* parent = nullptr);
    void set_properties(std::vector<PropertyDescriptor> props);
    void clear();

private:
    void rebuild();
    QFormLayout*                         form_ = nullptr;
    std::vector<PropertyDescriptor>      props_;
};

}  // namespace simall::gui
