// =============================================================================
// SimAll Beta — Scripting subsystem
// File   : src/scripting/MacroRecorder.cpp
// =============================================================================
#include "scripting/MacroRecorder.hpp"

#include <fstream>
#include <sstream>

namespace simall::scripting
{

MacroRecorder::MacroRecorder() = default;

MacroRecorder::~MacroRecorder()
{
    if (listenerId_)
        CommandBus::instance().remove_listener(listenerId_);
}

void MacroRecorder::start()
{
    if (recording_)
        return;
    recording_ = true;
    listenerId_ = CommandBus::instance().add_listener([this](const ScriptableCommand& c) {
        if (recording_)
            commands_.push_back(c);
    });
}

void MacroRecorder::stop()
{
    recording_ = false;
}

void MacroRecorder::clear()
{
    commands_.clear();
}

void MacroRecorder::append(ScriptableCommand c)
{
    commands_.push_back(std::move(c));
}

std::string MacroRecorder::to_python_script(std::string_view header) const
{
    std::ostringstream os;
    os << "# Generated by SimAll MacroRecorder. Do not edit auto-headers.\n";
    if (!header.empty())
        os << "# " << header << '\n';
    os << "import simall\n\n";
    for (const auto& c : commands_)
        os << c.to_python_call("simall") << '\n';
    return os.str();
}

bool MacroRecorder::save_to_file(const std::string& path, std::string_view header) const
{
    std::ofstream f(path, std::ios::binary);
    if (!f)
        return false;
    f << to_python_script(header);
    return f.good();
}

} // namespace simall::scripting
